### ISSUE TITLE
Cycle warning module fetch

### ISSUE THREAD

**Issue by eikeland** [iaphub/react-native-iaphub#84] opened 2021-07-01 09:54 UTC
After installing this package i always get a console Cycle warning concerning fetch.

`Require cycle: node_modules/react-native/Libraries/Network/fetch.js -> node_modules/whatwg-fetch/dist/fetch.umd.js -> node_modules/react-native/Libraries/Network/fetch.js`

Are anyone else seeing this warning?

**Comment by iaphub** [comment] 2021-07-01 20:07
This warning is caused by react-native-fetch-polyfill, a dependency of the plugin.
It seems like the warning is a bug in react-native, we were able to fix it by adding a 'hack'(see link below), weird it is not working on your side. https://github.com/iaphub/react-native-iaphub/blob/55809e5268fc999b1ce97f545a8b4ad06a9c96ac/src/index.js#L7

**Comment by eikeland** [comment] 2021-07-01 20:27
I can se the hack you mention is added to the module, but it's not working. Im running on iOS if that matters.

**Comment by iaphub** [comment] 2021-07-03 08:20
What version of react native are you using?

**Comment by eikeland** [comment] 2021-07-06 12:00
Sorry for late reply, Im running version 0.64.1

**Comment by iaphub** [comment] 2021-07-08 17:59
Thanks for the info @eikeland, we'll take a look at that and comment this ticket to let you know if we find a workaround (closing it in the meantime).

**Closed by iaphub** 2021-07-08 17:59 UTC

**Comment by eikeland** [comment] 2021-07-08 18:06
Great, thanks.
